### ISSUE TITLE
Snitch rendering enabled on login

### ISSUE THREAD

**Issue by walkersgaming** [MrLittleKitty/Snitch-Master#27] opened 2017-03-08 20:06 UTC
For me whenever I login the snitch rendering is enabled, no idea if it's something I've done or if others experience the same.

**Comment by MrLittleKitty** [comment] 2017-03-09 06:27
Yeah I found the cause. Its just not saving the snitch lists at certain times when it should be.

I'm going to finish with the configurable quiet time feature that is in progress then I will be reworking rendering. Expect a fix for this with the rendering overhaul. 

(Reminder for me: lists.snitchListsChanged() should be called when render order changes, rendering state changes, literally when anything with the snitch lists change. Sadly though, this is gonna update journeymap and cause that terrible performance impact...rip)

**Comment by MrLittleKitty** [comment] 2017-04-04 07:09
Completed (probably?) as of https://github.com/MrLittleKitty/Snitch-Master/commit/29f3b734ca54c7ca808eb303be9e9a59e76c1c77

**Closed as completed by MrLittleKitty** 2017-04-04 07:09 UTC
Labels: bug
